trigger:
  - main

pool:
  name: 'Azuredevopspool'

variables:
  terraformVersion: '1.6.0'
  serviceConnection: 'AzureDevOps-Terraform'
  workingDirectory: 'terraform'

stages:
- stage: Terraform_Build
  displayName: "Terraform Build and Validation"
  jobs:
  - job: Terraform_Build_Job
    displayName: "Terraform Initialization and Validation"
    steps:

    # Install Terraform (Use correct extension)
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: $(terraformVersion)

    # Initialize Terraform
    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workingDirectory)
        backendType: 'azurerm'
        environmentServiceNameAzureRM: $(serviceConnection)

    # Validate Terraform
    - task: TerraformTaskV4@4
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: $(workingDirectory)

    # Terraform Plan
    - task: TerraformTaskV4@4
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(workingDirectory)
        environmentServiceNameAzureRM: $(serviceConnection)
        commandOptions: '-out=tfplan'

    # Publish Terraform Plan Artifact
    - task: PublishBuildArtifacts@1
      displayName: "Publish Terraform Plan"
      inputs:
        artifactName: 'terraform_plan'
        pathToPublish: '$(workingDirectory)/tfplan'

- stage: Terraform_Deploy
  displayName: "Terraform Apply"
  dependsOn: Terraform_Build
  condition: succeeded()
  jobs:
  - deployment: Terraform_Apply_Job
    displayName: "Terraform Apply to Azure"
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:

          # Install Terraform (Use correct extension)
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: $(terraformVersion)

          # Download Terraform Plan Artifact
          - task: DownloadBuildArtifacts@0
            displayName: "Download Terraform Plan"
            inputs:
              artifactName: 'terraform_plan'
              downloadPath: $(Pipeline.Workspace)

          # Apply Terraform Changes
          - task: TerraformTaskV4@4
            displayName: "Terraform Apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(workingDirectory)'
              commandOptions: '$(Pipeline.Workspace)/terraform_plan/tfplan'
              environmentServiceNameAzureRM: '$(serviceConnection)'
