trigger:
  - main  # Trigger on changes to main branch (adjust as needed)

pool:
  name: 'Azuredevopspool'  # Specify your self-hosted agent pool name

variables:
  terraformVersion: '1.5.7'  # Adjust Terraform version as needed
  workingDirectory: 'terraform'  # Path to Terraform code
  serviceConnection: 'azureterraform'  # Name of Azure DevOps service connection

stages:
  - stage: Terraform_Deploy
    displayName: 'Terraform Deployment'
    jobs:
      - job: Terraform_Apply
        displayName: 'Run Terraform'
        steps:
          # 📌 Checkout the repository
          - task: Checkout@1

          # 📌 Install Terraform
          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          # 📌 Initialize Terraform
          - task: TerraformCLI@2
            displayName: 'Terraform Init'
            inputs:
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendType: 'azurerm'
              backendServiceArm: $(serviceConnection)
              ensureBackend: true

          # 📌 Terraform Plan
          - task: TerraformCLI@2
            displayName: 'Terraform Plan'
            inputs:
              command: 'plan'
              workingDirectory: '$(workingDirectory)'
              environmentServiceName: $(serviceConnection)
