trigger:
- main

pool:
  name: 'Azuredevopspool'  # Ensure this is your self-hosted Windows agent pool

steps:
- script: |
    curl -LO https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_windows_amd64.zip
    unzip terraform_1.1.0_windows_amd64.zip
    move terraform.exe C:\Terraform
    setx PATH "%PATH%;C:\Terraform"
  displayName: 'Install Terraform'

- script: |
    set PATH=%PATH%;C:\Users\yashr\OneDrive\Desktop\Agent\vsts-agent-win-x64-4.251.0\_work\_tool\terraform\1.10.5\x64\
    terraform --version
  displayName: 'Verify Terraform Version'

- task: AzureCLI@2
  displayName: 'Terraform Init'
  inputs:
    azureSubscription: 'azureterraform'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init

- script: |
    terraform fmt -check -diff
  displayName: 'Terraform Format Check'

- script: |
    terraform validate
  displayName: 'Terraform Validate'

- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'azureterraform'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform plan -out=tfplan

- task: AzureCLI@2
  displayName: 'Terraform Apply'
  inputs:
    azureSubscription: 'azureterraform'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform apply -auto-approve tfplan
