trigger:
  - main  # Runs when code is pushed to the main branch

pool:
  name: 'Azuredevopspool'  # Use your self-hosted agent pool

stages:
  - stage: DeployInfra
    displayName: "Deploy Azure Infrastructure"
    jobs:
      - job: Terraform_Deployment
        displayName: "Terraform Deployment"
        steps:
        
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: 'latest'

          - task: TerraformCLI@2
            displayName: "Terraform Init"
            inputs:
              command: 'init'
              backendType: 'azurerm'
              backendServiceArm: 'testconnection'

          - task: TerraformCLI@2
            displayName: "Terraform Plan"
            inputs:
              command: 'plan'
              backendServiceArm: 'testconnection'

          - task: TerraformCLI@2
            displayName: "Terraform Apply"
            inputs:
              command: 'apply'
              backendServiceArm: 'testconnection'
              commandOptions: '-auto-approve'  # Automatically approve changes
