trigger:
- main

pool:
  name: 'Azuredevopspool'  # Ensure this is your self-hosted agent

steps:
- script: |
    if [ -d "/home/Terraform" ]; then
        rm -rf /home/Terraform
    fi
    mkdir -p /home/Terraform
    curl -LO "https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip"
    unzip terraform_1.1.0_linux_amd64.zip -d /home/Terraform
    echo "##vso[task.setvariable variable=PATH]$PATH:/home/Terraform"
  displayName: 'Install Terraform'

- script: |
    terraform --version
  displayName: 'Verify Terraform Version'

- task: AzureCLI@2
  displayName: 'Terraform Init'
  inputs:
    azureSubscription: 'azureterraform'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform init'
    useGlobalConfig: true

- script: |
    terraform fmt -check -diff
  displayName: 'Terraform Format Check'

- script: |
    terraform validate
  displayName: 'Terraform Validate'

- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'azureterraform'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform plan -out=tfplan'

- task: AzureCLI@2
  displayName: 'Terraform Apply'
  inputs:
    azureSubscription: 'azureterraform'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform apply -auto-approve tfplan'
    useGlobalConfig: true
