trigger:
  - main  

pool:
  name: 'Azuredevopspool'  

variables:
  terraformVersion: '1.5.7'
  workingDirectory: 'terraform'
  serviceConnection: 'azureterraform'

stages:
  - stage: Terraform_Deploy
    displayName: 'Terraform Deployment'
    jobs:
      - job: Terraform_Apply
        displayName: 'Run Terraform'
        steps:
          # Checkout code
          - task: Checkout@1

          # Install Terraform (Choose the correct task reference based on your installed extension)
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          # Initialize Terraform
          - task: TerraformCLI@2
            displayName: 'Terraform Init'
            inputs:
              command: 'init'
              workingDirectory: '$(workingDirectory)'
              backendType: 'azurerm'
              backendServiceArm: $(serviceConnection)
              ensureBackend: true

          # Terraform Plan
          - task: TerraformCLI@2
            displayName: 'Terraform Plan'
            inputs:
              command: 'plan'
              workingDirectory: '$(workingDirectory)'
              environmentServiceName: $(serviceConnection)

          # Terraform Apply
          - task: TerraformCLI@2
            displayName: 'Terraform Apply'
            inputs:
              command: 'apply'
              workingDirectory: '$(workingDirectory)'
              environmentServiceName: $(serviceConnection)
              commandOptions: '-auto-approve'
